### PR TITLE
Make mappings configurable

### PR DESCRIPTION
**Pull request by mudox**
Very useful tool, it's would be better if I can remap the default mappings.

### CODE REVIEW

**Comment by tpope** [comment]
You can already `map ... <Plug>...`. I need a more compelling argument to add a layer of indirection.

**Comment by Mudox** [comment]
Actually I just could not find a decent way to properly remap <buffer> K without touching source code,  which is defined in autocmd TypeFile without a <Plug> mapping.

**Comment by tpope** [comment]
I would accept an `if empty(mapcheck('K'))` around the mapping. This especially makes sense for `K` because we're matching it to a global default that has been overridden.

**Comment by tpope** [comment]
Make that `mapcheck('K', 'n')` to be exact.

**Comment by Mudox** [comment]
Thanks for the suggestion, I only added `mapcheck()` guard for 'K', removed all doc change because the source file itself is very obvious.
Then in vimrc a line
```vim
  autocmd FileType vim nmap <buffer> <silent> H <Plug>ScripteaseHelp<Cr>
```
will work.

**Comment by tpope** [comment]
Please squash into one commit, thanks.

**Pull request merged**
