### PR TITLE
Hid temp filename message && silent map q

### PR DESCRIPTION
**Pull request by wsdjeg**
@tpope I just add something to hide the message in the message area,and use silent map for q in priview windows

### CODE REVIEW

**Comment by wsdjeg** [comment]
@tpope ping

**Comment by tpope** [comment]
The silent map is fine but I don't see why hiding the tmp filename is a good idea. And you didn't follow contribution guidelines.

**Comment by wsdjeg** [comment]
oh sorry . I will read more about the contribution

来自我的华为手机

-------- 原始邮件 --------
主题：Re: [vim-scriptease] Hid temp filename message && silent map q (#24)
发件人：Tim Pope
收件人：tpope/vim-scriptease
抄送：Wang Shidong

The silent map is fine but I don't see why hiding the tmp filename is a good idea. And you didn't follow contribution guidelines.

---

**Comment by wsdjeg** [comment]
@tpope 
I think we do not need know the temp file name when we open a buffer for other info,such as verbose.
also just like most plugin exit with silent map `q`

**Comment by tpope** [comment]
No, we don't need to know it, but it shows in the statusline too, so it's not like you're fully hiding it. I am wary of doing a bunch of `echo` dark magic, which can sometimes cause "press enter" prompts in certain setups.

**Comment by wsdjeg** [comment]
>which can sometimes cause "press enter" prompts in certain setups.

this also what I am wary of.but I have used that formate in my own plugin Mysql.vim.after about 3mounth ,I nevner see the "press Enter".ok let me try with PR more times,and if we need hid the info in statusline,maybe a airline extra script needed

**Comment by wsdjeg** [comment]
@tpope for this PR, I just want make my cmdline looks clean, and the buffer mapping `q` (:bd), should be silent called. because sometimes I use cmdline to show message I need.
but `echon '\r\r'|echon ''` maybe is not good ideal, but do you know any other way?

**Comment by wsdjeg** [comment]
@tpope I use `silent! pedit temp` instead, so I think the PR is ready. 

rebased!

**Pull request closed without merging**
